include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Style
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_const_declarations
    - prefer_final_fields
    - prefer_final_locals
    - use_key_in_widget_constructors
    - sized_box_for_whitespace
    - avoid_unnecessary_containers
    - use_full_hex_values_for_flutter_colors
    - prefer_single_quotes

    # Documentation
    - public_member_api_docs
    - comment_references

    # Design
    - prefer_relative_imports
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - always_put_required_named_parameters_first

    # Performance
    - avoid_function_literals_in_foreach_calls
    - prefer_for_elements_to_map_fromIterable
    - prefer_if_elements_to_conditional_expressions
    - prefer_spread_collections

    # Safety
    - avoid_print
    - avoid_web_libraries_in_flutter
    - no_logic_in_create_state
    - use_build_context_synchronously

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/generated_plugin_registrant.dart"

  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
